ADD_DEFINITIONS("-DMATH_USE_OPENGL")
ADD_DEFINITIONS("-DMATH_RIGHTHANDED_CAMERA")
ADD_DEFINITIONS("-DMATH_AVX")
add_definitions(-D_CRT_SECURE_NO_WARNINGS)

INCLUDE_DIRECTORIES(${CMGDK_PATH}/3rdpty/MathGeoLib/src)

add_subdirectory(${CMGDK_PATH}/3rdpty/MathGeoLib)
