SET(CMAKE_ALLOW_LOOSE_LOOP_CONSTRUCTS TRUE)

OPTION(BUILD_OPENAL_LIB			"Build OpenAL Library"						FALSE	)

IF(BUILD_OPENAL_LIB)
    SET(VORBIS_DECODE_LIBRARY VORBIS CACHE STRING "Vorbis Decode select")
    SET_PROPERTY(CACHE VORBIS_DECODE_LIBRARY PROPERTY STRINGS VORBIS TREMOR TREMOLO)

    IF(UNIX)
    # 	IF(BUILD_OPENAL_LIB)
    # 		FIND_PATH(OPENAL_INCLUDE_DIR
    # 			NAMES al.h
    # 			HINTS
    # 			/usr/include/AL
    # 			/usr/local/include/AL)
    # 		INCLUDE_DIRECTORIES(${OPENAL_INCLUDE_DIR})
    #
    # 		FIND_PATH(OPENAL_LIBRARY_DIR
    # 			NAMES libopenal.so
    # 			HINTS
    # 			${LIB_3RD_FIND_HINT})
    # 		LINK_DIRECTORIES(${OPENAL_LIBRARY_DIR})
    # 	ENDIF(BUILD_OPENAL_LIB)
    ELSEIF(WIN32)
    # 	IF(BUILD_OPENAL_LIB)
    # 		FIND_PATH(OPENAL_INCLUDE_DIR
    # 			NAMES al.h
    # 			HINTS
    # 			${INC_3RD_FIND_HINT})
    # 		INCLUDE_DIRECTORIES(${OPENAL_INCLUDE_DIR})
    #
    # 		FIND_PATH(OPENAL_LIBRARY_DIR
    # 			NAMES libopenal.lib
    # 			HINTS
    # 			${LIB_3RD_FIND_HINT})
    # 		LINK_DIRECTORIES(${OPENAL_LIBRARY_DIR})
    # 	ENDIF(BUILD_OPENAL_LIB)
    ENDIF()

	SET(HGL_AUDIO_LIB CM.OpenALEE)
ENDIF(BUILD_OPENAL_LIB)
