#ifndef HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_RT_INCLUDE
#define HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_RT_INCLUDE

namespace hgl
{
	//windows 8 for ARM

}//namespace hgl
#endif//HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_RT_INCLUDE
