#ifndef HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_6_INCLUDE
#define HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_6_INCLUDE

namespace hgl
{
	//windows vista/2008/7/2008r2/8

}//namespace hgl
#endif//HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_6_INCLUDE
