#ifndef HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_5_INCLUDE
#define HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_5_INCLUDE

namespace hgl
{
	//windows 2000/xp/2003

}//namespace hgl
#endif//HGL_PLATFORM_DESKTOP_MICROSOFT_WINDOWS_NT_5_INCLUDE
